# Project: 动画版本2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = add.o buy.o cartoonoutput.o divide.o main.o path.o input.o decide.o
LINKOBJ  = add.o buy.o cartoonoutput.o divide.o main.o path.o input.o decide.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lgraphics64 -lgdi32 -limm32 -lmsimg32 -lole32 -loleaut32 -lwinmm -luuid -mwindows -mwindows -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = 动画版本2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

add.o: add.cpp
	$(CPP) -c add.cpp -o add.o $(CXXFLAGS)

buy.o: buy.cpp
	$(CPP) -c buy.cpp -o buy.o $(CXXFLAGS)

cartoonoutput.o: cartoonoutput.cpp
	$(CPP) -c cartoonoutput.cpp -o cartoonoutput.o $(CXXFLAGS)

divide.o: divide.cpp
	$(CPP) -c divide.cpp -o divide.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

path.o: path.cpp
	$(CPP) -c path.cpp -o path.o $(CXXFLAGS)

input.o: input.cpp
	$(CPP) -c input.cpp -o input.o $(CXXFLAGS)

decide.o: decide.cpp
	$(CPP) -c decide.cpp -o decide.o $(CXXFLAGS)
